I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 264, in script
    mc "Oookay?"
Exception: Sayer 'mc' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 264, in script
    mc "Oookay?"
  File "C:\Users\roast\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\roast\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'mc' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Plenty O Fish 
Wed Nov 30 23:43:26 2022
